# ğŸŒ General settings
title: "Alberto Cotumaccio's Website"
description: "Alberto Cotumaccio's website"
author: "Alberto Cotumaccio"
email: ""
language: en

# ğŸ“‚ Base settings
baseurl: ""
url: "https://albertocotumaccio.github.io"

# ğŸ“„ File and directory settings
exclude:
  - "README.md"
  - "Gemfile"
  - "Gemfile.lock"
  - "node_modules"
  - ".jekyll-metadata"

# ğŸ”— Social media links
social:
  github: "https://github.com/albertoCotumaccio"
  linkedin: "https://www.linkedin.com/in/alberto-cotumaccio-8b8443229/"
  twitter: "https://twitter.com/Albecotu"

# ğŸ“œ Blog settings
permalink: /blog/:year/:month/:day/
paginate: 5
paginate_path: "/blog/page:num/"

# ğŸ¨ Theme e plugins
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-archives

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

# ğŸ”„ Build settings
future: false
